name: Project checks

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  policy:
    uses: petohorvath/nixos-project-policy/.github/workflows/check.yml@v0.1.1
    with:
      project: nixos-registry
      policy_version: v0.1.1
